main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('index/', views.home, name='home'),
    path('biodata/', views.biodata, name='biodata'),
    path('pengalaman/', views.pengalaman, name='pengalaman'),
    path('pendidikan/', views.pendidikan, name='pendidikan'),
    path('story1/', views.story1, name='story1'),
    path('jadwal/', views.jadwal, name='jadwal'),
    path('tambah/', views.tambah, name='tambah'),
    path('hapus/<int:nomor>', views.hapus, name='hapus'),
    path('detail/<int:nomor>', views.detail, name='detail'),
]

story4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('story6.urls')),
    path('', include('story7.urls')),
    path('', include('story8.urls')),
    path('', include('story9.urls')),
]

story6/urls.py
from django.urls import path

from . import views

app_name = 'story6'

urlpatterns = [
    path('kegiatan/', views.kegiatan, name='kegiatan'),
    path('tambah_kegiatan/', views.tambah_kegiatan, name='tambah_kegiatan'),
    path('detail_kegiatan/<int:nomor>', views.detail_kegiatan, name='detail_kegiatan'),
    path('hapus_kegiatan/<int:nomor>', views.hapus_kegiatan, name='hapus_kegiatan'),
    path('tambah_peserta/<int:nomor>', views.tambah_peserta, name='tambah_peserta'),
    path('hapus_peserta/<int:nomor>', views.hapus_peserta, name='hapus_peserta'),
]

story7/urls.py
from django.urls import path

from . import views

app_name = 'story7'

urlpatterns = [
    path('story7/', views.story7, name='story7'),
]

story8/urls.py
from django.urls import path
from . import views

app_name = 'story8'

urlpatterns = [
    path('story8/', views.story8, name='story8'),
    path('story8/data/', views.data, name='data'),
]

story9/urls.py
from django.urls import path
from . import views

app_name = 'story9'

urlpatterns = [
    path('story9/', views.story9, name='story9'),
    path('story9/register/', views.register, name='register'),
    path('story9/login/', views.log_in, name='login'),
    path('story9/logout/', views.log_out, name='logout'),
]

story9/models.py
from django.db import models

# Create your models here.

story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
# Create your views here.
def story9(request):
	return render(request, 'story9/story9.html')

def register(request):
	if request.method == "POST":
		username = request.POST.get('username')
		password = request.POST.get('password')
		if User.objects.filter(username = username).exists():
			messages.error(request, 'Username sudah ada')
			return redirect('story9:register')
		user = User.objects.create_user(username = username)
		user.set_password(password)
		user.save()
		return redirect('story9:login')
	return render(request, 'story9/register.html')

def log_in(request):
	if request.method == "POST":
		username = request.POST.get('username')
		password = request.POST.get('password')
		user = authenticate(username = username, password = password)
		if user is not None:
			if user.is_active:
				login(request, user)	
			return redirect('story9:story9')
		else:
			messages.error(request, 'Username / Password salah')
			return redirect('story9:login')
	return render(request, 'story9/login.html')

def log_out(request):
	logout(request)
	return redirect('story9:story9')

story9/templates/story9/login.html
<!doctype html>
{%load static %}
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <title>Story9</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/style5.css' %}"> 
    </head>
    <body style="background-color: #f2f2f2;">
        <nav class="navbar sticky-top navbar-expand-lg navbar-light" style="background-color: #56ccf2;">
            <a class="navbar-brand" href="{% url 'main:home' %}"><img src="{% static 'story3/home.png' %}" style="width:42px;height:42px;"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" href="{% url 'main:biodata' %}">Biodata</a>
                    <a class="nav-link" href="{% url 'main:pengalaman' %}">Pengalaman</a>
                    <a class="nav-link" href="{% url 'main:pendidikan' %}">Pendidikan</a>
                    <a class="nav-link" href="{% url 'main:story1' %}">Story 1</a>
                    <a class="nav-link" href="{% url 'main:jadwal' %}">Jadwal</a>
                    <a class="nav-link" href="{% url 'story6:kegiatan' %}">Kegiatan</a>
                    <a class="nav-link" href="{% url 'story7:story7' %}">Story7</a>
                    <a class="nav-link" href="{% url 'story8:story8' %}">Story8</a>
                    <a class="nav-link" href="{% url 'story9:story9' %}">Story9</a>
                </div>
            </div>
            <div class="navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'story9:story9' %}">USERNAME</a>
                {% else %}
                <a class="nav-link" href="{% url 'story9:login' %}">Log in</a>
                <a class="nav-link" href="{% url 'story9:register' %}">Register</a>
                {% endif %}
            </div>
        </nav>
        

        <center>
            <h1 class = "jarak">Login</h1>
        </center>

        <div class="mx-5">
            <form method="post">
                {% csrf_token %}
                Username
                <div class="form-group"><input class="form-control" type="text" name = "username"></div>
                Password
                <div class="form-group"><input class="form-control" type="password" name = "password"></div>
                <div class="form-group text-center">
                    <button class="btn btn-primary" type="submit">Login</button>
                </div>
            </form>
        </div>

        {% if messages %}
            {% for message in messages %}
            <center>
                <h3> {{ message|safe }} </h3>
            </center>
            {% endfor %}
        {% endif %}


        <div class = "jarakb"></div>
        <nav class="navbar fixed-bottom justify-content-center navbar-light jaraka" style="background-color: #2d9cdb;">
            <a class = "jarakkk" href="https://www.instagram.com/faustaadp/"><img src="{% static 'story3/ig.png' %}" style="width:56px;height:56px;"></a>
            <a class = "jarakkk" href="https://twitter.com/FaustaAD"><img src="{% static 'story3/tw.png' %}" style="width:56px;height:56px;"></a>
            <a class = "jarakkk" href="https://www.facebook.com/fausta.ad/"><img src="{% static 'story3/fb.png' %}" style="width:56px;height:56px;"></a>
        </nav>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

story9/templates/story9/register.html
<!doctype html>
{%load static %}
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <title>Story9</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/style5.css' %}"> 
    </head>
    <body style="background-color: #f2f2f2;">
        <nav class="navbar sticky-top navbar-expand-lg navbar-light" style="background-color: #56ccf2;">
            <a class="navbar-brand" href="{% url 'main:home' %}"><img src="{% static 'story3/home.png' %}" style="width:42px;height:42px;"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" href="{% url 'main:biodata' %}">Biodata</a>
                    <a class="nav-link" href="{% url 'main:pengalaman' %}">Pengalaman</a>
                    <a class="nav-link" href="{% url 'main:pendidikan' %}">Pendidikan</a>
                    <a class="nav-link" href="{% url 'main:story1' %}">Story 1</a>
                    <a class="nav-link" href="{% url 'main:jadwal' %}">Jadwal</a>
                    <a class="nav-link" href="{% url 'story6:kegiatan' %}">Kegiatan</a>
                    <a class="nav-link" href="{% url 'story7:story7' %}">Story7</a>
                    <a class="nav-link" href="{% url 'story8:story8' %}">Story8</a>
                    <a class="nav-link" href="{% url 'story9:story9' %}">Story9</a>
                </div>
            </div>
            <div class="navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'story9:story9' %}">USERNAME</a>
                {% else %}
                <a class="nav-link" href="{% url 'story9:login' %}">Log in</a>
                <a class="nav-link" href="{% url 'story9:register' %}">Register</a>
                {% endif %}
            </div>
        </nav>
        
        <center>
            <h1 class = "jarak">Register</h1>
        </center>

        <div class="mx-5">
            <form method="post">
                {% csrf_token %}
                Username
                <div class="form-group"><input class="form-control" type="text" name = "username"></div>
                Password
                <div class="form-group"><input class="form-control" type="password" name = "password"></div>
                <div class="form-group text-center">
                    <button class="btn btn-primary" type="submit">Register</button>
                </div>
            </form>
        </div>

        {% if messages %}
            {% for message in messages %}
            <center>
                <h3> {{ message|safe }} </h3>
            </center>
            {% endfor %}
        {% endif %}


        <div class = "jarakb"></div>
        <nav class="navbar fixed-bottom justify-content-center navbar-light jaraka" style="background-color: #2d9cdb;">
            <a class = "jarakkk" href="https://www.instagram.com/faustaadp/"><img src="{% static 'story3/ig.png' %}" style="width:56px;height:56px;"></a>
            <a class = "jarakkk" href="https://twitter.com/FaustaAD"><img src="{% static 'story3/tw.png' %}" style="width:56px;height:56px;"></a>
            <a class = "jarakkk" href="https://www.facebook.com/fausta.ad/"><img src="{% static 'story3/fb.png' %}" style="width:56px;height:56px;"></a>
        </nav>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

story9/templates/story9/story9.html
<!doctype html>
{%load static %}
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <title>Story9</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/style5.css' %}"> 
    </head>
    <body style="background-color: #f2f2f2;">
        <nav class="navbar sticky-top navbar-expand-lg navbar-light" style="background-color: #56ccf2;">
            <a class="navbar-brand" href="{% url 'main:home' %}"><img src="{% static 'story3/home.png' %}" style="width:42px;height:42px;"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" href="{% url 'main:biodata' %}">Biodata</a>
                    <a class="nav-link" href="{% url 'main:pengalaman' %}">Pengalaman</a>
                    <a class="nav-link" href="{% url 'main:pendidikan' %}">Pendidikan</a>
                    <a class="nav-link" href="{% url 'main:story1' %}">Story 1</a>
                    <a class="nav-link" href="{% url 'main:jadwal' %}">Jadwal</a>
                    <a class="nav-link" href="{% url 'story6:kegiatan' %}">Kegiatan</a>
                    <a class="nav-link" href="{% url 'story7:story7' %}">Story7</a>
                    <a class="nav-link" href="{% url 'story8:story8' %}">Story8</a>
                    <a class="nav-link" href="{% url 'story9:story9' %}">Story9</a>
                </div>
            </div>
            <div class="navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'story9:story9' %}">{{user.username}}</a>
                <a class="nav-link" href="{% url 'story9:logout' %}">Log Out</a>
                {% else %}
                <a class="nav-link" href="{% url 'story9:login' %}">Log in</a>
                <a class="nav-link" href="{% url 'story9:register' %}">Register</a>
                {% endif %}
            </div>
        </nav>
        
        <center>
            <h1 class = "jarak">Story 9</h1>
        </center>
        <br>
        <br>
        <br>
        <br>
        {% if user.is_authenticated %}
        <center>
            <br>
            <h2> Selamat datang {{user.username}} </h2>
        </center>
        {% else %}
        <center>
            <h2> Anda belum log in. Silahkan 
                <a href="{% url 'story9:login' %}"> log in</a>
             terlebih dahulu </h2>
            <br>
            <br>

            <h2> Jika belum memiliki akun silahkan 
                <a href="{% url 'story9:register' %}"> register</a>
            </h2>
        </center>
        {% endif %}


        <div class = "jarakb"></div>
        <nav class="navbar fixed-bottom justify-content-center navbar-light jaraka" style="background-color: #2d9cdb;">
            <a class = "jarakkk" href="https://www.instagram.com/faustaadp/"><img src="{% static 'story3/ig.png' %}" style="width:56px;height:56px;"></a>
            <a class = "jarakkk" href="https://twitter.com/FaustaAD"><img src="{% static 'story3/tw.png' %}" style="width:56px;height:56px;"></a>
            <a class = "jarakkk" href="https://www.facebook.com/fausta.ad/"><img src="{% static 'story3/fb.png' %}" style="width:56px;height:56px;"></a>
        </nav>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>