main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('index/', views.home, name='home'),
    path('biodata/', views.biodata, name='biodata'),
    path('pengalaman/', views.pengalaman, name='pengalaman'),
    path('pendidikan/', views.pendidikan, name='pendidikan'),
    path('story1/', views.story1, name='story1'),
    path('jadwal/', views.jadwal, name='jadwal'),
    path('tambah/', views.tambah, name='tambah'),
    path('hapus/<int:nomor>', views.hapus, name='hapus'),
    path('detail/<int:nomor>', views.detail, name='detail'),
]

story4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('story6.urls')),
    path('', include('story7.urls')),
    path('', include('story8.urls')),
    path('', include('story9.urls')),
]

story6/urls.py
from django.urls import path

from . import views

app_name = 'story6'

urlpatterns = [
    path('kegiatan/', views.kegiatan, name='kegiatan'),
    path('tambah_kegiatan/', views.tambah_kegiatan, name='tambah_kegiatan'),
    path('detail_kegiatan/<int:nomor>', views.detail_kegiatan, name='detail_kegiatan'),
    path('hapus_kegiatan/<int:nomor>', views.hapus_kegiatan, name='hapus_kegiatan'),
    path('tambah_peserta/<int:nomor>', views.tambah_peserta, name='tambah_peserta'),
    path('hapus_peserta/<int:nomor>', views.hapus_peserta, name='hapus_peserta'),
]

story6/models.py
from django.db import models

# Create your models here.

class Kegiatan(models.Model):
	nama = models.CharField(max_length = 50)
	deskripsi = models.CharField(max_length = 50)

class Peserta(models.Model):
	nama = models.CharField(max_length = 50)
	kegiatan = models.ForeignKey(Kegiatan, on_delete=models.CASCADE)

story6/forms.py
from django import forms
from .models import Kegiatan, Peserta

class FormKegiatan(forms.ModelForm):
    class Meta:
        model = Kegiatan
        fields = ['nama', 'deskripsi']
        widgets = {
            'nama' : forms.TextInput(attrs={'class': 'form-control'}),
            'deskripsi' : forms.TextInput(attrs={'class': 'form-control'}),
        }

class FormPeserta(forms.ModelForm):
    class Meta:
        model = Peserta
        fields = ['nama']
        widgets = {
            'nama' : forms.TextInput(attrs={'class': 'form-control'}),
        }

story6/views.py
from django.shortcuts import render, redirect
from .models import Kegiatan, Peserta
from .forms import FormKegiatan, FormPeserta
# Create your views here.
def kegiatan(request):
	kegiatan = Kegiatan.objects.all()
	peserta = Peserta.objects.all()
	context = {'kegiatan': kegiatan, 'peserta': peserta}
	return render(request, 'story6/kegiatan.html', context)

def tambah_kegiatan(request):
	form = FormKegiatan()
	if request.method == "POST":
		form = FormKegiatan(request.POST)
		if form.is_valid():
			form.save()
			return redirect('story6:kegiatan')
	context = {'form' : form}
	return render(request, 'story6/tambah_kegiatan.html', context)

def detail_kegiatan(request, nomor):
	kegiatan = Kegiatan.objects.get(id = nomor)
	peserta = Peserta.objects.all()
	context = {'kegiatan': kegiatan, 'peserta': peserta}
	return render(request, 'story6/detail_kegiatan.html', context)

def hapus_kegiatan(request, nomor):
	kegiatan = Kegiatan.objects.get(id = nomor)
	kegiatan.delete()
	return redirect('story6:kegiatan')

def tambah_peserta(request, nomor):
	form = FormPeserta()
	if request.method == "POST":
		form = FormPeserta(request.POST)
		if form.is_valid():
			peserta = Peserta(nama=form.data['nama'], kegiatan = Kegiatan.objects.get(id = nomor))
			peserta.save()
			return redirect('story6:kegiatan')
	context = {'form' : form}
	return render(request, 'story6/tambah_peserta.html', context)

def hapus_peserta(request, nomor):
	peserta = Peserta.objects.get(id = nomor)
	id = peserta.kegiatan.id
	peserta.delete()
	return redirect('/detail_kegiatan/' + str(id))

story6/templates/story6/detail_kegiatan.html
{% extends 'main/base.html' %}
<!doctype html>
{% block content %}
{% load static %}
<title>Jadwal</title>
<center>
	<h1 class = "jarak">
		{{kegiatan.nama}}
		<a type="button" data-toggle="modal" data-target="#exampleModal" class="btn btn-danger">Hapus</a>
	</h1>
</center>
<div class = "mx-5">
	<h3>Deskripsi</h3>
	<h4>{{kegiatan.deskripsi}}</h4>
</div>
</br>
<div class = "mx-5">
	<h3>
		Peserta
		<a class="btn btn-primary" href = "{% url 'story6:tambah_peserta' kegiatan.id %}">Tambah</a>
	</h3>
	<table class="table table-hover table-responsive-sm .table-borderless">
	{% for pst in peserta %}
		{% if pst.kegiatan == kegiatan %}
		<tr>
			<th>
				<h5>
					{{pst.nama}}
				</h5>
			</th>
			<th class = "text-right">
				<a type="button" href = "{% url 'story6:hapus_peserta' pst.id %}" class="btn btn-danger">Hapus</a>
			</th>
		</tr>
		{% endif %}
	{% endfor %}
	</table>
</div>

</br>
<center>
	<a type="button" href = "{% url 'story6:kegiatan' %}" class="btn btn-primary">Kembali</a>
</center>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h6 class="modal-title" id="exampleModalLabel">Peringatan</h6>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
				<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<h5 class="modal-title" id="exampleModalLabel">Apakah anda yakin untuk mengapus kegiatan {{kegiatan.nama}} ?</h5>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary" data-dismiss="modal">Tidak</button>
				<a type="button" href = "{% url 'story6:hapus_kegiatan' kegiatan.id %}" class="btn btn-danger">Hapus</a>
			</div>
		</div>
	</div>
</div>

{% endblock %}

story6/templates/story6/kegiatan.html
{% extends 'main/base.html' %}
<!doctype html>
{% block content %}
{% load static %}
<title>Kegiatan</title>
<center>
	<h1 class = "jarak">Kegiatan</h1>
</center>
<div class="row row-cols-1 row-cols-md-3 m-5">
	{% for kgt in kegiatan %}
	<div class="col mb-4">
		<div class="card">
			<div class="card-body">
				<h3 class = "text-center"> 
					<a class="card-title text-center" href = "{% url 'story6:detail_kegiatan' kgt.id %}">{{kgt.nama}}</a>
				</h3>
				{% for pst in peserta %}
					{% if pst.kegiatan == kgt %}
					<h5>
						<li> {{pst.nama}} </li>
					</h5>
					{% endif %}
				{% endfor %}
				<div class = "text-center m-3"> 
					<a class="btn btn-primary" href="/tambah_peserta/{{kgt.id}}">Tambah Peserta</a>
				</div>
			</div>
		</div>
	</div>
	
{% endfor %}
</div>
<center>
	<a type="button" href = "{% url 'story6:tambah_kegiatan' %}" class="btn btn-primary">Tambah</a>
</center>



{% endblock %}

story6/templates/story6/tambah_kegiatan.html
{% extends 'main/base.html' %}
<!doctype html>
{% block content %}
{% load static %}
<title>Tambah</title>
<center>
	<h1 class = "jarak">Tambah Kegiatan</h1>
</center>
<form class = "ml-5 mr-5 mt-2" method="POST">
	{% csrf_token %}
	<div class="form-group">
		<label for="nama">Nama Kegiatan</label> {{form.nama}}
	</div>
	<div class="form-group">
		<label for="deskripsi">Deskripsi</label> {{form.deskripsi}}
	</div>
	<center>
		<button type="submit" class="btn btn-primary">Submit</button>
	</center>
</form>
{% endblock %}

story6/templates/story6/tambah_peserta.html
{% extends 'main/base.html' %}
<!doctype html>
{% block content %}
{% load static %}
<center>
	<h1 class = "jarak">Tambah Peserta</h1>
</center>
<title>Tambah Peserta</title>
<form class = "ml-5 mr-5 mt-2" method="POST">
	{% csrf_token %}
	<div class="form-group">
		<label for="nama">Nama</label> {{form.nama}}
	</div>
	<center>
		<button type="submit" class="btn btn-primary">Submit</button>
	</center>
</form>
{% endblock %}