main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('index/', views.home, name='home'),
    path('biodata/', views.biodata, name='biodata'),
    path('pengalaman/', views.pengalaman, name='pengalaman'),
    path('pendidikan/', views.pendidikan, name='pendidikan'),
    path('story1/', views.story1, name='story1'),
    path('jadwal/', views.jadwal, name='jadwal'),
    path('tambah/', views.tambah, name='tambah'),
    path('hapus/<int:nomor>', views.hapus, name='hapus'),
    path('detail/<int:nomor>', views.detail, name='detail'),
]

story4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('story6.urls')),
    path('', include('story7.urls')),
    path('', include('story8.urls')),
    path('', include('story9.urls')),
]

story6/urls.py
from django.urls import path

from . import views

app_name = 'story6'

urlpatterns = [
    path('kegiatan/', views.kegiatan, name='kegiatan'),
    path('tambah_kegiatan/', views.tambah_kegiatan, name='tambah_kegiatan'),
    path('detail_kegiatan/<int:nomor>', views.detail_kegiatan, name='detail_kegiatan'),
    path('hapus_kegiatan/<int:nomor>', views.hapus_kegiatan, name='hapus_kegiatan'),
    path('tambah_peserta/<int:nomor>', views.tambah_peserta, name='tambah_peserta'),
    path('hapus_peserta/<int:nomor>', views.hapus_peserta, name='hapus_peserta'),
]

story7/urls.py
from django.urls import path

from . import views

app_name = 'story7'

urlpatterns = [
    path('story7/', views.story7, name='story7'),
]

story8/urls.py
from django.urls import path
from . import views

app_name = 'story8'

urlpatterns = [
    path('story8/', views.story8, name='story8'),
    path('story8/data/', views.data, name='data'),
]

story9/urls.py
from django.urls import path
from . import views

app_name = 'story9'

urlpatterns = [
    path('story9/', views.story9, name='story9'),
    path('story9/register/', views.register, name='register'),
    path('story9/login/', views.log_in, name='login'),
    path('story9/logout/', views.log_out, name='logout'),
]

main/models.py
from django.db import models

# Create your models here.

class Jadwal(models.Model):
	nama = models.CharField(max_length = 50)
	dosen = models.CharField(max_length = 50)
	sks = models.PositiveIntegerField(default = 1)
	deskripsi = models.CharField(max_length = 100)
	semester = models.CharField(max_length = 6, choices= [('Ganjil', 'Ganjil'), ('Genap', 'Genap')], default = ('Ganjil', 'Ganjil'));
	tahun = models.CharField(max_length = 9, choices= [('2019/2020', '2019/2020'), ('2020/2021', '2020/2021'), ('2021/2022', '2021/2022'), ('2022/2023', '2022/2023')], default = ('2020/2021', '2020/2021'));
	ruang = models.CharField(max_length = 50)

main/forms.py
from django import forms
from .models import Jadwal

class FormJadwal(forms.ModelForm):
    class Meta:
        model = Jadwal
        fields = ['nama', 'dosen', 'sks', 'deskripsi', 'semester', 'tahun', 'ruang']
        widgets = {
            'nama' : forms.TextInput(attrs={'class': 'form-control'}),
            'dosen' : forms.TextInput(attrs={'class': 'form-control'}),
            'sks' : forms.NumberInput(attrs={'class': 'form-control'}),
            'deskripsi' : forms.TextInput(attrs={'class': 'form-control'}),
            'semester' : forms.Select(attrs={'class': 'form-control'}),
            'tahun' : forms.Select(attrs={'class': 'form-control'}),
            'ruang' : forms.TextInput(attrs={'class': 'form-control'}),
        }

main/views.py
from django.shortcuts import render, redirect
from .models import Jadwal
from .forms import FormJadwal

def home(request):
	return render(request, 'main/index.html')

def biodata(request):
	return render(request, 'main/biodata.html')

def pengalaman(request):
	return render(request, 'main/pengalaman.html')

def pendidikan(request):
	return render(request, 'main/pendidikan.html')

def story1(request):
	return render(request, 'main/story1.html')

def jadwal(request):
	jadwal = Jadwal.objects.all()
	context = {'jadwal': jadwal}
	return render(request, 'main/jadwal.html', context)

def tambah(request):
	form = FormJadwal()
	if request.method == "POST":
		form = FormJadwal(request.POST)
		if form.is_valid():
			form.save()
			return redirect('main:jadwal')
	context = {'form' : form}
	return render(request, 'main/tambah.html', context)

def hapus(request, nomor):
	jadwal = Jadwal.objects.get(id = nomor)
	jadwal.delete()
	return redirect('main:jadwal')

def detail(request, nomor):
	jadwal = Jadwal.objects.get(id = nomor)
	context = {'jadwal': jadwal}
	return render(request, 'main/detail.html', context)

main/templates/main/base.html
<!doctype html>
{%load static %}
<html lang="en">
	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
		{% block head %}
		{% endblock %}
		<link rel="stylesheet" type="text/css" href="{% static 'css/style5.css' %}"> 
	</head>
	<body style="background-color: #f2f2f2;">
		<nav class="navbar sticky-top navbar-expand-lg navbar-light" style="background-color: #56ccf2;">
  			<a class="navbar-brand" href="{% url 'main:home' %}"><img src="{% static 'story3/home.png' %}" style="width:42px;height:42px;"></a>
  			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    			<span class="navbar-toggler-icon"></span>
  			</button>
  			<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    			<div class="navbar-nav">
					<a class="nav-link" href="{% url 'main:biodata' %}">Biodata</a>
					<a class="nav-link" href="{% url 'main:pengalaman' %}">Pengalaman</a>
					<a class="nav-link" href="{% url 'main:pendidikan' %}">Pendidikan</a>
					<a class="nav-link" href="{% url 'main:story1' %}">Story 1</a>
					<a class="nav-link" href="{% url 'main:jadwal' %}">Jadwal</a>
					<a class="nav-link" href="{% url 'story6:kegiatan' %}">Kegiatan</a>
					<a class="nav-link" href="{% url 'story7:story7' %}">Story7</a>
					<a class="nav-link" href="{% url 'story8:story8' %}">Story8</a>
					<a class="nav-link" href="{% url 'story9:story9' %}">Story9</a>
    			</div>
  			</div>
		</nav>
        {% block content %}
        {% endblock %}
		<div class = "jarakb"></div>
		<nav class="navbar fixed-bottom justify-content-center navbar-light jaraka" style="background-color: #2d9cdb;">
			<a class = "jarakkk" href="https://www.instagram.com/faustaadp/"><img src="{% static 'story3/ig.png' %}" style="width:56px;height:56px;"></a>
			<a class = "jarakkk" href="https://twitter.com/FaustaAD"><img src="{% static 'story3/tw.png' %}" style="width:56px;height:56px;"></a>
			<a class = "jarakkk" href="https://www.facebook.com/fausta.ad/"><img src="{% static 'story3/fb.png' %}" style="width:56px;height:56px;"></a>
		</nav>
		<!-- Optional JavaScript -->
		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
		<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
	    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
        {% block tambahjs %}
        {% endblock %}

  </body>
</html>

main/templates/main/biodata.html
{% extends 'main/base.html' %}
<!doctype html>
{% block content %}
{% load static %}
<title>Biodata</title>
<h1 style="text-align:center"; class = "jarak"> Biodata </h1>
<div class="container">
	<div class="row">
		<div class="col">
			<center>
				<img src="{% static 'story3/faus.png' %}" width="290" height="385">
			</center>
		</div>
		<div class="col-7">
			<h3 class = "jarakt">Nama : Raden Fausta Anugrah Dianparama</h3>
			<h3 class = "jarakt">Perguruan Tinggi : Universitas Indonesia</h3>
			<h3 class = "jarakt">Fakultas : Ilmu Komputer</h3>
			<h3 class = "jarakt">Jurusan : Ilmu Komputer</h3>
			<h3 class = "jarakt">Angkatan : 2019</h3>
			<h3 class = "jarakt">NPM : 1906285560</h3>
			<h3 class = "jarakt">Hobi : Competitive Programming</h3>
		</div>
	</div>
</div>
{% endblock %}

main/templates/main/detail.html
{% extends 'main/base.html' %}
<!doctype html>
{% block content %}
{% load static %}
<title>Jadwal</title>
<center>
	<h1 class = "jarak">{{jadwal.nama}}</h1>
</center>
<div class = "m-5">
	<table class="table table-bordered">
		<tbody>
	  	<tr>
			<th>SKS</th>
			<td>{{jadwal.sks}}</td>
		</tr>
		<tr>
			<th>Dosen</th>
			<td>{{jadwal.dosen}}</td>
		</tr>
		<tr>
			<th>Deskripsi</th>
			<td>{{jadwal.deskripsi}}</td>
		</tr>
		<tr>
			<th>Semester</th>
			<td>{{jadwal.semester}}</td>
		</tr>
		<tr>
			<th>Tahun</th>
			<td>{{jadwal.tahun}}</td>
		</tr>
		<tr>
			<th>Ruang</th>
			<td>{{jadwal.ruang}}</td>
		</tr>
	  </tbody>
	</table>
</div>
<center>
	<a type="button" href = "{% url 'main:jadwal' %}" class="btn btn-primary">Kembali</a>
</center>

{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}
<!doctype html>
{% block content %}
{% load static %}
<title>Fausta</title>
<center>
	<h1 class = "jarak">Raden Fausta Anugrah Dianparama</h1>
	<img src="{% static 'story3/TH46.png' %}" class="jarak" width="300" height="300">
</center>
<center>
	<div>
		<a type="button" href = "{% url 'main:biodata' %}" class="btn btn-primary jarak besar">Biodata</a>
		<a type="button" href = "{% url 'main:pengalaman' %}" class="btn btn-primary jarak besar">Pengalaman</a>
		<a type="button" href = "{% url 'main:pendidikan' %}" class="btn btn-primary jarak besar">Pendidikan</a>
	</div>
	<div>
		<a type="button" href = "{% url 'main:story1' %}" class="btn btn-primary jarak besar">Story 1</a>
		<a type="button" href = "{% url 'main:jadwal' %}" class="btn btn-primary jarak besar">Jadwal</a>
		<a type="button" href = "{% url 'story6:kegiatan' %}" class="btn btn-primary jarak besar">Kegiatan</a>
	</div>
	<div>
		<a type="button" href = "{% url 'story7:story7' %}" class="btn btn-primary jarak besar">Story 7</a>
		<a type="button" href = "{% url 'story8:story8' %}" class="btn btn-primary jarak besar">Story 8</a>
		<a type="button" href = "{% url 'story9:story9' %}" class="btn btn-primary jarak besar">Story 9</a>
	</div>
</center>
{% endblock %}

main/templates/main/jadwal.html
{% extends 'main/base.html' %}
<!doctype html>
{% block content %}
{% load static %}
<title>Jadwal</title>
<center>
	<h1 class = "jarak">Jadwal</h1>
</center>
<div class = "m-5">
	<table class="table table-striped table-hover table-bordered table-responsive-sm">
		<thead class="thead-dark">
		    <tr>
				<th scope="col">Mata Kuliah</th>
				<th scope="col">SKS</th>
				<th scope="col">Dosen</th>
				<th scope="col">Ruang</th>
				<th scope="col"></th>
			</tr>
		</thead>
		<tbody>
	  	{% for jdw in jadwal %}
		  	<tr>
				<th>
					<a href = "{% url 'main:detail' jdw.id %}">
						{{jdw.nama}}
					</a>
				</th>
				<td>{{jdw.sks}}</td>
				<td>{{jdw.dosen}}</td>
				<td>{{jdw.ruang}}</td>
				<td>
					<center>
						<a type="button" href = "{% url 'main:hapus' jdw.id %}" class="btn btn-danger">Hapus</a>
					</center>
				</td>
			</tr>
		{% endfor %}
	  </tbody>
	</table>
</div>
<center>
	<a type="button" href = "{% url 'main:tambah' %}" class="btn btn-primary">Tambah</a>
</center>

{% endblock %}

main/templates/main/pendidikan.html
{% extends 'main/base.html' %}
{% block content %}
{% load static %}
<title>Pendidikan</title>
<h1 style="text-align:center"; class = "jarak"> Pendidikan </h1>
<div class="container">
	<div class="row">
		<div class="col">
			<center>
				<h3 class = "jarak">SD</h3>
				<img class = "jarak" src="{% static 'story3/lw.png' %}" width="180" height="180">
				<h4 class = "jarak">SD Negeri Lempuyangwangi</h4>
				<h4 class = "jarak">(2007 - 2013)</h4>
			</center>
		</div>
		<div class="col">
			<center>
				<h3 class = "jarak">SMP</h3>
				<img class = "jarak" src="{% static 'story3/smp1.png' %}" width="180" height="180">
				<h4 class = "jarak">SMP Negeri 1 Yogyakarta</h4>
				<h4 class = "jarak">(2013 - 2016)</h4>
			</center>
		</div>
		<div class="col">
			<center>
				<h3 class = "jarak">SMA</h3>
				<img class = "jarak" src="{% static 'story3/sma1.png' %}" width="180" height="180">
				<h4 class = "jarak">SMA Negeri 1 Yogyakarta</h4>
				<h4 class = "jarak">(2016 - 2019)</h4>
			</center>
		</div>
		<div class="col">
			<center>
				<h3 class = "jarak">Perguruan Tinggi</h3>
				<img class = "jarak" src="{% static 'story3/ui.png' %}" width="180" height="180">
				<h4 class = "jarak">Universitas Indonesia</h4>
				<h4 class = "jarak">(2019 - Sekarang)</h4>
			</center>
		</div>
	</div>
</div>
{% endblock %}

main/templates/main/pengalaman.html
{% extends 'main/base.html' %}
{% block content %}
{% load static %}
<title>Pengalaman</title>
<h1 style="text-align:center"; class = "jarak"> Pengalaman </h1>
<div class="container">
	<div class="row">
		<div class="col-8">
			<h3 class = "jarakt">Kepanitiaan</h3>
			<h4 class = "jaraktm">Scientific Committee CPC Compfest 12</h4>
			<h3 class = "jarakt">Prestasi</h3>
			<h4 class = "jaraktm">Medali Perak IOI 2019</h4>
			<h4 class = "jaraktm">Medali Perunggu APIO 2019</h4>
			<h4 class = "jaraktm">Medali Emas NOI Singapore 2019</h4>
			<h4 class = "jaraktm">Medali Perak OSN 2017</h4>
		</div>
		<div class="col">
			<center>
				<img class = "jarakdk" src="{% static 'story3/faus2.png' %}" width="270" height="180">
				<img class = "jarakdk" src="{% static 'story3/faus3.png' %}" width="270" height="200">
			</center>
		</div>
	</div>
</div>
{% endblock %}

main/templates/main/story1.html
{% extends 'main/base.html' %}
{% block content %}
{% load static %}
<style>
	table, th, td {
		margin: auto;
		border: 1px solid black;
			padding: 10px;
	}
</style>
<title>Story 1</title>
<h3 style="text-align:center;">Raden Fausta Anugrah Dianparama</h3>
<center>
	<img src="{% static 'story1/TH46.jpg' %}" class="tengah" width="300" height="300">
</center>
<h3 style="text-align:center;">Panggilan : Fausta</h3>
<h3 style="text-align:center;">NPM : 1906285560</h3>
<h3 style="text-align:center;">Angkatan : 2019</h3>
<h3 style="text-align:center;">Kuliah : Universitas Indonesia</h3>
<h3 style="text-align:center;">Hobi : Competitive Programming</h3>
<h3 style="text-align:center">Saya berasal dari Yogyakarta. Saya adalah mahasiswa Ilmu Komputer Fasilkom UI angkatan 2019. Saya diterima melalui jalur Olimpiade</h3>
<h3 style="text-align:center"> Riwayat Pendidikan :</h3>
<table style="text-align: center;">
	<tr> 
		<th> Pendidikan </th>
		<th> Sekolah / Universitas </th>
		<th> Tahun </th>
	</tr> 
	<tr> 
		<td> SD </td>
		<td> SD Negeri Lempuyangwangi </td>
		<td> 2007 - 2013 </td>
	</tr> 
	<tr> 
		<td> SMP </td>
		<td> SMP Negeri 1 Yogyakarta </td>
		<td> 2013 - 2016 </td>
	</tr> 
	<tr> 
		<td> SMA </td>
		<td> SMA Negeri 1 Yogyakarta </td>
		<td> 2016 - 2019 </td>
	</tr> 
	<tr> 
		<td> Universitas </td>
		<td> Universitas Indonesia </td>
		<td> 2019 - Sekarang </td>
	</tr> 
</table>
<br></br>
<center>
	<a href="https://www.instagram.com/faustaadp/"><img src="{% static 'story1/ig.png' %}" style="width:42px;height:42px;"></a>
	<a href="https://twitter.com/FaustaAD"><img src="{% static 'story1/tw.png' %}" style="width:42px;height:42px;"></a>
	<a href="https://www.facebook.com/fausta.ad/"><img src="{% static 'story1/fb.png' %}" style="width:42px;height:42px;"></a>
</center>
{% endblock %}

main/templates/main/tambah.html
{% extends 'main/base.html' %}
<!doctype html>
{% block content %}
{% load static %}
<title>Tambah</title>
<form class = "ml-5 mr-5 mt-2" method="POST">
	{% csrf_token %}
	<div class="row">
		<div class="form-group col-10">
			<label for="nama">Mata Kuliah</label> {{form.nama}}
		</div>
		<div class="form-group col">
			<label for="sks">SKS</label> {{form.sks}}
		</div>
	</div>
	<div class="form-group">
		<label for="dosen">Dosen</label> {{form.dosen}}
	</div>
	<div class="row">
		<div class="form-group col-sm">
			<label for="semester">Semester</label> {{form.semester}}
		</div>
		<div class="form-group col-sm">
			<label for="tahun">Tahun</label> {{form.tahun}}
		</div>
		<div class="form-group col-sm">
			<label for="ruang">Ruang</label> {{form.ruang}}
		</div>
	</div>
	<div class="form-group">
		<label for="deskripsi">Deskripsi</label> {{form.deskripsi}}
	</div>
	<center>
		<button type="submit" class="btn btn-primary">Submit</button>
	</center>
</form>
{% endblock %}